# -*- coding: utf-8 -*-
"""excerse3_withAPI_013&132ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9MScrnmr_ocxGHHT-fOVXWc3drulDS8
"""

import requests

url = 'https://id.wikipedia.org/api/rest_v1/page/summary/Pesta_Olahraga_Asia_2026'
headers = {'User-Agent': 'Mozilla/5.0'}

api_request = requests.get(url, headers=headers)
api_request

import requests
import json

# API Wikipedia/Wikimedia bersifat publik dan GRATIS,
# jadi kamu tidak memerlukan api_key (bisa diset string kosong atau diisi acak untuk tugas)
api_key = ''

query = 'Pesta_Olahraga_Asia_2026'

# Gunakan prop=links untuk mendapatkan array daftar nama/tautan
url = f'https://id.wikipedia.org/w/api.php?action=query&format=json&titles={query}&prop=links'

headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)
data = response.json()
data

# Ambil dictionary 'pages' dari JSON Wikipedia
pages = data['query']['pages']

# Mengambil objek halaman (menggunakan list(pages.values())[0] karena key-nya berupa ID acak)
page = list(pages.values())[0]

# Melakukan perulangan untuk mengambil daftar nama dan ns (namespace)
for item in page['links']:
    print(item['title'], "-", item['ns'])

import json
import requests

query = 'Pesta_Olahraga_Asia_2026'
url = f'https://id.wikipedia.org/w/api.php?action=query&format=json&titles={query}&prop=links'

headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)
data = response.json()

# Menyimpan hasil JSON ke dalam file response.json
with open('response.json', 'w') as f:
    json.dump(data, f, indent=4)

import json

# Membaca file response.json yang telah disimpan
with open("response.json", "r") as f:
    data = json.load(f)

# Menampilkan isi data JSON yang berhasil dibaca
data

import json
import pandas as pd

# 1. Buka file response.json
with open("response.json", "r") as f:
    data = json.load(f)

titles = []
namespaces = []

# 2. Ambil objek 'pages' (menggunakan list(pages.values())[0] karena ID-nya acak)
pages = data["query"]["pages"]
page = list(pages.values())[0]

# 3. Looping untuk mengambil 'title' dan 'ns' dari daftar links
for item in page.get("links", []):
    titles.append(item.get("title"))
    namespaces.append(item.get("ns"))

# 4. Buat DataFrame Pandas
df = pd.DataFrame({'Title': titles, 'Namespace': namespaces})
df

