# -*- coding: utf-8 -*-
"""Exercise 4_132&013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZd1Z7hsZ2cyDbcVM6_3TWQECaAPuAXJ
"""

import requests
from bs4 import BeautifulSoup

titles = []


target_count = 100
page = 1

while len(titles) < target_count:
  url = f"http://books.toscrape.com/catalogue/page-{page}.html"

  response = requests.get(url)

  if response.status_code != 200:
    print(f'Gagal mengakses halaman {page}')
    break

  soup = BeautifulSoup(response.text, 'html.parser')

  books = soup.find_all('article', class_='product_pod')

  for book in books:
    if len(titles) >= target_count:
      break

    tag_a = book.find('h3').find('a')
    title = tag_a['title']


    titles.append(title)


  page += 1

import pandas as pd
df = pd.DataFrame({
    'title': titles
})
df

titles_str = ", ".join(df["title"].astype(str))
print(titles_str)

#remove hashtag

import re

remove_hashtag = re.sub(r'#\d+', '', titles_str)

remove_hashtag_text = re.sub(r'#\w+', '', remove_hashtag)
print(remove_hashtag_text)

#lower

lower = str.lower(remove_hashtag_text)
print(lower)

#remove punctuation

import string
punc = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', punc))

hasil_rp = remove_punctuation(lower)
print(hasil_rp)

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

print(stopwords.words('english'))

text = '''a light in the attic tipping the velvet soumission sharp objects sapiens
a brief history of humankind the requiem red the dirty little secrets of getting your
dream job the coming woman a novel based on the life of the infamous feminist victoria
woodhull the boys in the boat nine americans and their epic quest for gold at the 1936
berlin olympics the black maria starving hearts triangular trade trilogy  shakespeares
sonnets set me free scott pilgrims precious little life scott pilgrim  rip it up and
start again our band could be your life scenes from the american indie underground 19811991
olio mesaerion the best science fiction stories 18001849 libertarianism for beginners
its only the himalayas in her wake how music works foolproof preserving a guide to
small batch jams jellies pickles condiments and more a foolproof guide to making small
batch jams jellies pickles condiments and more chase me paris nights  black dust birdsong
a story in pictures americas cradle of quarterbacks western pennsylvanias football factory
from johnny unitas to joe montana aladdin and his wonderful lamp worlds elsewhere journeys
around shakespeareâs globe wall and piece the four agreements a practical guide to personal
freedom the five love languages how to express heartfelt commitment to your mate the elephant
tree the bear and the piano sophies world penny maybe maude 18831993she grew up with the
country in a dark dark wood behind closed doors you cant bury them all poems slow states
of collapse poems reasons to stay alive private paris private   wake up your life free
your soul find your tribe without borders wanderlove  when we collided we love you charlie
freeman untitled collection sabbath poems 2014 unseen city the majesty of pigeons the
discreet charm of snails  other wonders of the urban wilderness unicorn tracks unbound
how eight technologies made us human transformed society and brought our world to the
brink tsubasa world chronicle 2 tsubasa world chronicle  throwing rocks at the google
bus how growth became the enemy of prosperity this one summer thirst the torch is
passed a harding family story the secret of dreadwillow carse the pioneer woman cooks
dinnertime comfort classics freezer food 16minute meals and other delicious ways to
solve supper the past never ends the natural history of us the fine art of pretending
the nameless city the nameless city  the murder that never was forensic instincts
the most perfect thing inside and outside a birds egg the mindfulness and acceptance
workbook for anxiety a guide to breaking free from anxiety phobias and worry using
acceptance and commitment therapy the lifechanging magic of tidying up the japanese
art of decluttering and organizing the inefficiency assassin time management tactics
for working smarter not longer the gutsy girl escapades for your life of epic adventure
the electric pencil drawings from inside state hospital no 3 the death of humanity and
the case for life the bulletproof diet lose up to a pound a day reclaim energy and focus
upgrade your life the art forger the age of genius the seventeenth century and the birth
of the modern mind the activists tao te ching ancient advice for a modern revolution
spark joy an illustrated master class on the art of organizing and tidying up soul reader
security saga volume 6 saga collected editions  saga volume 5 saga collected editions
reskilling america learning to labor in the twentyfirst century rat queens vol 3 demons
rat queens collected editions 15 princess jellyfish 2in1 omnibus vol 01 princess jellyfish
2in1 omnibus  princess between worlds wideawake princess  pop gun war volume 1 gift political
suicide missteps peccadilloes bad calls backroom hijinx sordid pasts rotten breaks and just
plain dumb mistakes in the annals of american politics patience outcast vol 1 a darkness
surrounds him outcast  orange the complete collection 1 orange the complete collection
online marketing for busy authors a stepbystep guide on a midnight clear obsidian lux
my paris kitchen recipes and stories masks and shadows mama tried traditional italian
cooking for the screwed crude vegan and tattooed lumberjanes vol 2 friendship to the
max lumberjanes 8 lumberjanes vol 1 beware the kitten holy lumberjanes 4 lumberjanes
vol 3 a terrible plan lumberjanes 12 layered baking building and styling spectacular
cakes judo seven steps to black belt an introductory guide for beginners join in the
country we love my family divided
'''


sw = set(stopwords.words('english'))
def remove_stopwords(text):

  return " ".join([word for word in str(text).split() if word not in sw])

hasil_st = remove_stopwords(text)
print(hasil_st)

def remove_numeric(text):
  return re.sub(r'\d+', '', text)

hasil_rn = remove_numeric(hasil_st)
print(hasil_rn)

text_split = hasil_rn.split()
print(text_split)

from nltk.stem import SnowballStemmer

text_split = [i for i in text_split if i.isascii() and i.isalpha() and len(i)>1]       #menghilangkan kata 'shakespeareâs'
print(text_split)

text_stemmer = SnowballStemmer('english')
stemmed = [text_stemmer.stem(i) for i in text_split]
print(stemmed)

from wordcloud import WordCloud
import matplotlib.pyplot as plt

text = '''a light in the attic tipping the velvet soumission sharp objects sapiens
a brief history of humankind the requiem red the dirty little secrets of getting your
dream job the coming woman a novel based on the life of the infamous feminist victoria
woodhull the boys in the boat nine americans and their epic quest for gold at the 1936
berlin olympics the black maria starving hearts triangular trade trilogy  shakespeares
sonnets set me free scott pilgrims precious little life scott pilgrim  rip it up and
start again our band could be your life scenes from the american indie underground 19811991
olio mesaerion the best science fiction stories 18001849 libertarianism for beginners
its only the himalayas in her wake how music works foolproof preserving a guide to
small batch jams jellies pickles condiments and more a foolproof guide to making small
batch jams jellies pickles condiments and more chase me paris nights  black dust birdsong
a story in pictures americas cradle of quarterbacks western pennsylvanias football factory
from johnny unitas to joe montana aladdin and his wonderful lamp worlds elsewhere journeys
around shakespeareâ€™s globe wall and piece the four agreements a practical guide to personal
freedom the five love languages how to express heartfelt commitment to your mate the elephant
tree the bear and the piano sophies world penny maybe maude 18831993she grew up with the
country in a dark dark wood behind closed doors you cant bury them all poems slow states
of collapse poems reasons to stay alive private paris private   wake up your life free
your soul find your tribe without borders wanderlove  when we collided we love you charlie
freeman untitled collection sabbath poems 2014 unseen city the majesty of pigeons the
discreet charm of snails  other wonders of the urban wilderness unicorn tracks unbound
how eight technologies made us human transformed society and brought our world to the
brink tsubasa world chronicle 2 tsubasa world chronicle  throwing rocks at the google
bus how growth became the enemy of prosperity this one summer thirst the torch is
passed a harding family story the secret of dreadwillow carse the pioneer woman cooks
dinnertime comfort classics freezer food 16minute meals and other delicious ways to
solve supper the past never ends the natural history of us the fine art of pretending
the nameless city the nameless city  the murder that never was forensic instincts
the most perfect thing inside and outside a birds egg the mindfulness and acceptance
workbook for anxiety a guide to breaking free from anxiety phobias and worry using
acceptance and commitment therapy the lifechanging magic of tidying up the japanese
art of decluttering and organizing the inefficiency assassin time management tactics
for working smarter not longer the gutsy girl escapades for your life of epic adventure
the electric pencil drawings from inside state hospital no 3 the death of humanity and
the case for life the bulletproof diet lose up to a pound a day reclaim energy and focus
upgrade your life the art forger the age of genius the seventeenth century and the birth
of the modern mind the activists tao te ching ancient advice for a modern revolution
spark joy an illustrated master class on the art of organizing and tidying up soul reader
security saga volume 6 saga collected editions  saga volume 5 saga collected editions
reskilling america learning to labor in the twentyfirst century rat queens vol 3 demons
rat queens collected editions 15 princess jellyfish 2in1 omnibus vol 01 princess jellyfish
2in1 omnibus  princess between worlds wideawake princess  pop gun war volume 1 gift political
suicide missteps peccadilloes bad calls backroom hijinx sordid pasts rotten breaks and just
plain dumb mistakes in the annals of american politics patience outcast vol 1 a darkness
surrounds him outcast  orange the complete collection 1 orange the complete collection
online marketing for busy authors a stepbystep guide on a midnight clear obsidian lux
my paris kitchen recipes and stories masks and shadows mama tried traditional italian
cooking for the screwed crude vegan and tattooed lumberjanes vol 2 friendship to the
max lumberjanes 8 lumberjanes vol 1 beware the kitten holy lumberjanes 4 lumberjanes
vol 3 a terrible plan lumberjanes 12 layered baking building and styling spectacular
cakes judo seven steps to black belt an introductory guide for beginners join in the
country we love my family divided
'''

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='white',
    max_words=500
).generate(text)

plt.figure(figsize=(7, 4))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

