# -*- coding: utf-8 -*-
"""Exercise 5_013 & 132.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lphFk_nKYWO6t3P-msTUX7i1ivoJdSnr
"""

import warnings
warnings.filterwarnings(action = 'ignore')

import pandas as pd
import ast

df = pd.read_csv('hasil_preprocessing.csv')
df = df.dropna().reset_index(drop=True)
df['tokens'] = df['tokens'].apply(ast.literal_eval)
df_pre = df['tokens']

print(type(df_pre[0]), df_pre[0])
print(df.shape)

"""#BAG OF WORDS"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(analyzer=lambda x: x)
X = vectorizer.fit_transform(df_pre)
df_bow = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out(), index=df['title'])
df_bow

"""#TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(analyzer=lambda x: x)
X_tfidf = tfidf.fit_transform(df_pre)
df_FE = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out(), index=df['title'])
df_FE

#cek

for i in range(3):
  r = df_FE.iloc[i]
  print(df_FE.index[i], '->', r[r > 0].round(3).to_dict())

"""#Build Word2Vec n FastText"""

!pip install gensim

sentences = df_pre.tolist()
print(len(sentences), sentences[:3])

from gensim.models import Word2Vec, FastText

w2v = Word2Vec(sentences, vector_size=50, window=3, min_count=1,
              sg=1, epochs=100, seed=42, workers=1)

ft = FastText(sentences, vector_size=50, window=3, min_count=1,
              sg=1, epochs=100, min_n=2, max_n=4, seed=42, workers=1)

print(len(w2v.wv), len(ft.wv))
print(w2v.wv.most_similar('life', topn=5))
print(ft.wv.most_similar('life', topn=5))

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

def plot_embedding(model, title, n_words=50):
    words = model.wv.index_to_key[:n_words]
    xy = PCA(n_components=2).fit_transform([model.wv[w] for w in words])
    plt.figure(figsize=(12, 8))
    plt.scatter(xy[:, 0], xy[:, 1], alpha=0.6)
    for (x, y), w in zip(xy, words):
        plt.annotate(w, (x, y), fontsize=9)
    plt.title(title)
    plt.show()

plot_embedding(w2v, 'Word2Vec (PCA)')
plot_embedding(ft, 'FastText (PCA)')