# -*- coding: utf-8 -*-
"""Web Scraping HTML_132&013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zis_Ofbth4zZVUruu5XwFSUgNLF0LIvk
"""

!pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

titles = []
links = []
prices = []

target_count = 100
page = 1

while len(titles) < target_count:
  url = f"http://books.toscrape.com/catalogue/page-{page}.html"

  response = requests.get(url)

  if response.status_code != 200:
    print(f'Gagal mengakses halaman {page}')
    break

  soup = BeautifulSoup(response.text, 'html.parser')

  books = soup.find_all('article', class_='product_pod')

  for book in books:
    if len(titles) >= target_count:
      break

    tag_a = book.find('h3').find('a')
    title = tag_a['title']

    link_relatif = tag_a['href']
    link_lengkap = f"http://books.toscrape.com/catalogue/{link_relatif}"

    price = book.find('p', class_='price_color').text.strip()

    titles.append(title)
    links.append(link_lengkap)
    prices.append(price)

  page += 1

len(titles)

import pandas as pd
df = pd.DataFrame({
    'title': titles,
    'link': links,
    'price': prices
})
df

